spring.application.name=Finguard

spring.datasource.url=jdbc:postgresql://localhost:5432/finguard
spring.datasource.username=postgres
spring.datasource.password=postgres2211

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
